version: '3'

services:
  app:
    image: mediawiki:lts
    restart: unless-stopped
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${HOSTNAME}"
      traefik.port: '80'
    # If you don't want to use a reverse proxy (not suitable for production!)
    # ports:
    #  - "80:80"
    volumes:
      - images:/var/www/html/images
      # After initial setup, download LocalSettings.php to the volume directory
      # and uncomment the following line and use compose to restart the 
      # mediawiki service
      # - config:/var/www/html/LocalSettings.php
    depends_on:
      - db

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./docker-volume/db:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - db.env
  parsoid:
    image: thenets/parsoid:0.10
    environment:
      PARSOID_DOMAIN_hostname: "https://${HOSTNAME}/w/api.php"
  redis:
    image: redis

volumes:
  config:
  images:
